// Release helper: stamps the CLI version into every report-writing skill.
//
// Reads `packageVersion` from lib/src/version.dart and rewrites
//  - the `| Generated by | Somnio CLI v<version> |` row in every
//    skills/*/assets/report-template.md, skills/*/SKILL.md and
//    skills/*/agents/*.md that carries one, and
//  - `SOMNIO_VERSION` in skills/dora-metrics/scripts/dora_metrics.py.
//
// Idempotent: a second run on a stamped tree changes nothing. Run from cli/:
//
//   dart run tool/stamp_version.dart
import 'dart:io';

import 'package:path/path.dart' as p;

final _versionPattern = RegExp(r"const packageVersion = '([^']+)';");
final _rowPattern = RegExp(r'^\| Generated by \|.*\|[ \t]*$', multiLine: true);
final _doraPattern = RegExp(r'^SOMNIO_VERSION = "[^"]*"', multiLine: true);

void main() {
  final cliRoot = _findCliRoot();
  final repoRoot = p.dirname(cliRoot);
  final versionSource =
      File(p.join(cliRoot, 'lib', 'src', 'version.dart')).readAsStringSync();
  final match = _versionPattern.firstMatch(versionSource);
  if (match == null) {
    stderr.writeln('Could not read packageVersion from lib/src/version.dart');
    exit(1);
  }
  final version = match.group(1)!;
  final row = '| Generated by | Somnio CLI v$version |';

  final changed = <String>[];
  final skillsDir = Directory(p.join(repoRoot, 'skills'));
  final files = skillsDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .where((f) {
    final rel = p.relative(f.path, from: skillsDir.path).split(p.separator);
    return rel.length >= 2 &&
        (rel[1] == 'SKILL.md' && rel.length == 2 ||
            rel[1] == 'agents' && rel.length == 3 ||
            rel.length == 3 &&
                rel[1] == 'assets' &&
                rel[2] == 'report-template.md');
  }).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in files) {
    final text = file.readAsStringSync();
    if (!_rowPattern.hasMatch(text)) continue;
    final updated = text.replaceAll(_rowPattern, row);
    if (updated != text) {
      file.writeAsStringSync(updated);
      changed.add(p.relative(file.path, from: repoRoot));
    }
  }

  final dora = File(
      p.join(repoRoot, 'skills', 'dora-metrics', 'scripts', 'dora_metrics.py'));
  final doraText = dora.readAsStringSync();
  if (!_doraPattern.hasMatch(doraText)) {
    stderr.writeln('SOMNIO_VERSION constant not found in dora_metrics.py');
    exit(1);
  }
  final doraUpdated =
      doraText.replaceFirst(_doraPattern, 'SOMNIO_VERSION = "$version"');
  if (doraUpdated != doraText) {
    dora.writeAsStringSync(doraUpdated);
    changed.add(p.relative(dora.path, from: repoRoot));
  }

  if (changed.isEmpty) {
    stdout.writeln('Already stamped with v$version, nothing to change.');
  } else {
    stdout.writeln('Stamped v$version in ${changed.length} file(s):');
    changed.forEach((f) => stdout.writeln('  $f'));
  }
}

String _findCliRoot() {
  var dir = Directory.current;
  while (true) {
    if (File(p.join(dir.path, 'pubspec.yaml')).existsSync() &&
        File(p.join(dir.path, 'lib', 'src', 'version.dart')).existsSync()) {
      return dir.path;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      stderr.writeln('Run this from the cli/ directory.');
      exit(1);
    }
    dir = parent;
  }
}
