// Release helper: stamps the CLI version into every report-writing skill.
//
// Reads `packageVersion` from lib/src/version.dart and rewrites
//  - the `| Generated by | Somnio CLI v<version> |` row in every
//    skills/*/assets/report-template.md, skills/*/SKILL.md and
//    skills/*/agents/*.md that carries one, and
//  - `SOMNIO_VERSION` in skills/dora-metrics/scripts/dora_metrics.py.
//
// Idempotent: a second run on a stamped tree changes nothing. Run from cli/:
//
//   dart run tool/stamp_version.dart
import 'dart:io';

import 'package:path/path.dart' as p;

final _versionPattern = RegExp(r"const packageVersion = '([^']+)';");
final _rowPattern = RegExp(r'^\| Generated by \|.*\|[ \t]*$', multiLine: true);
final _doraPattern = RegExp(r'^SOMNIO_VERSION = "[^"]*"', multiLine: true);

/// What a stamping pass did.
class StampResult {
  StampResult(this.changed, this.missingRow);

  /// Repo-relative paths that were rewritten.
  final List<String> changed;

  /// Repo-relative paths of report-writing templates with no
  /// `| Generated by |` row (or no template at all).
  final List<String> missingRow;
}

/// Whether a skill writes a report: its SKILL.md declares
/// `Report Metadata (MANDATORY)` or it ships an `assets/report-template.md`,
/// whether or not that template still has a `Generated by` row.
///
/// This is a deliberate superset of `_declaredReportSkills` in
/// test/src/content/version_stamp_test.dart. That rule counts a template
/// only when it carries the row; here a template that lost its row must
/// still count, because that is exactly the case this helper reports.
bool _writesReport(Directory skill) {
  final skillMd = File(p.join(skill.path, 'SKILL.md'));
  final template = File(p.join(skill.path, 'assets', 'report-template.md'));
  final declaresMetadata = skillMd.existsSync() &&
      skillMd.readAsStringSync().contains('Report Metadata (MANDATORY)');
  return declaresMetadata || template.existsSync();
}

/// Stamps [version] under [repoRoot] and reports report-writing templates
/// that have no `Generated by` row. Throws [StateError] if the DORA
/// `SOMNIO_VERSION` constant is missing.
StampResult stampVersion(String repoRoot, String version) {
  final row = '| Generated by | Somnio CLI v$version |';

  final changed = <String>[];
  final missingRow = <String>[];
  final skillsDir = Directory(p.join(repoRoot, 'skills'));
  final files = skillsDir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('.md'))
      .where((f) {
    final rel = p.relative(f.path, from: skillsDir.path).split(p.separator);
    return rel.length >= 2 &&
        (rel[1] == 'SKILL.md' && rel.length == 2 ||
            rel[1] == 'agents' && rel.length == 3 ||
            rel.length == 3 &&
                rel[1] == 'assets' &&
                rel[2] == 'report-template.md');
  }).toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final file in files) {
    final text = file.readAsStringSync();
    if (!_rowPattern.hasMatch(text)) continue;
    final updated = text.replaceAll(_rowPattern, row);
    if (updated != text) {
      file.writeAsStringSync(updated);
      changed.add(p.relative(file.path, from: repoRoot));
    }
  }

  final skills = skillsDir.listSync().whereType<Directory>().toList()
    ..sort((a, b) => a.path.compareTo(b.path));
  for (final skill in skills.where(_writesReport)) {
    final template = File(p.join(skill.path, 'assets', 'report-template.md'));
    if (!template.existsSync() ||
        !_rowPattern.hasMatch(template.readAsStringSync())) {
      missingRow.add(p.relative(template.path, from: repoRoot));
    }
  }

  final dora = File(
      p.join(repoRoot, 'skills', 'dora-metrics', 'scripts', 'dora_metrics.py'));
  final doraText = dora.readAsStringSync();
  if (!_doraPattern.hasMatch(doraText)) {
    throw StateError('SOMNIO_VERSION constant not found in dora_metrics.py');
  }
  final doraUpdated =
      doraText.replaceFirst(_doraPattern, 'SOMNIO_VERSION = "$version"');
  if (doraUpdated != doraText) {
    dora.writeAsStringSync(doraUpdated);
    changed.add(p.relative(dora.path, from: repoRoot));
  }

  return StampResult(changed, missingRow);
}

void main() {
  final code = runStamp(_findCliRoot());
  if (code != 0) exit(code);
}

/// Stamps the repo that contains [cliRoot] and returns the process exit code:
/// 0 when clean, 1 on a setup error, 2 when a report-writing template has no
/// `Generated by` row.
///
/// Progress goes to [out] and problems to [err], which default to [stdout]
/// and [stderr].
int runStamp(String cliRoot, {StringSink? out, StringSink? err}) {
  final outSink = out ?? stdout;
  final errSink = err ?? stderr;
  final repoRoot = p.dirname(cliRoot);
  final versionSource =
      File(p.join(cliRoot, 'lib', 'src', 'version.dart')).readAsStringSync();
  final match = _versionPattern.firstMatch(versionSource);
  if (match == null) {
    errSink.writeln('Could not read packageVersion from lib/src/version.dart');
    return 1;
  }
  final version = match.group(1)!;

  final StampResult result;
  try {
    result = stampVersion(repoRoot, version);
  } on StateError catch (e) {
    errSink.writeln(e.message);
    return 1;
  }

  if (result.changed.isEmpty) {
    outSink.writeln('Already stamped with v$version, nothing to change.');
  } else {
    outSink.writeln('Stamped v$version in ${result.changed.length} file(s):');
    result.changed.forEach((f) => outSink.writeln('  $f'));
  }

  if (result.missingRow.isNotEmpty) {
    errSink.writeln('Report-writing templates without a `| Generated by |` '
        'row (not stamped):');
    result.missingRow.forEach((f) => errSink.writeln('  $f'));
    return 2;
  }
  return 0;
}

String _findCliRoot() {
  var dir = Directory.current;
  while (true) {
    if (File(p.join(dir.path, 'pubspec.yaml')).existsSync() &&
        File(p.join(dir.path, 'lib', 'src', 'version.dart')).existsSync()) {
      return dir.path;
    }
    final parent = dir.parent;
    if (parent.path == dir.path) {
      stderr.writeln('Run this from the cli/ directory.');
      exit(1);
    }
    dir = parent;
  }
}
