import 'dart:io';

import 'package:somnio/src/runner/template_version.dart';
import 'package:test/test.dart';

String _template(String stamp) => '# Report\n\n## Report Metadata\n\n'
    '| Field | Value |\n|-------|-------|\n'
    '| Generated by | $stamp |\n| Skill | example-health-audit |\n';

void main() {
  group('readTemplateVersion', () {
    test('reads the stamped version', () {
      expect(readTemplateVersion(_template('Somnio CLI v3.2.5')), '3.2.5');
    });

    test('returns null for the vX.Y.Z placeholder', () {
      expect(readTemplateVersion(_template('Somnio CLI vX.Y.Z')), isNull);
    });

    test('accepts CRLF line endings', () {
      final crlf = _template('Somnio CLI v3.2.5').replaceAll('\n', '\r\n');
      expect(readTemplateVersion(crlf), '3.2.5');
    });

    test('tolerates extra spaces around the cells', () {
      const row = '|   Generated by   |   Somnio CLI v3.2.5   |\n';
      expect(readTemplateVersion(row), '3.2.5');
    });

    test('returns null for the plugin placeholder', () {
      expect(
        readTemplateVersion(_template('[Plugin Name] v[Plugin Version]')),
        isNull,
      );
    });

    test('returns null for vunknown', () {
      expect(readTemplateVersion(_template('Somnio CLI vunknown')), isNull);
    });

    test('returns null for an empty string', () {
      expect(readTemplateVersion(''), isNull);
    });

    test('returns null when several rows make the stamp ambiguous', () {
      final twice = _template('Somnio CLI v1.0.0') +
          '| Generated by | Somnio CLI v2.0.0 |\n';
      expect(readTemplateVersion(twice), isNull);
    });

    test('ignores a row inside a fenced code block', () {
      final fenced = '```\n| Generated by | Somnio CLI v9.9.9 |\n```\n'
          '${_template('Somnio CLI v3.2.5')}';
      expect(readTemplateVersion(fenced), '3.2.5');
    });

    test('returns null when the row is missing', () {
      expect(readTemplateVersion('# Report\n'), isNull);
    });
  });

  group('readTemplateVersionFromFile', () {
    test('returns null for a missing file without throwing', () {
      expect(readTemplateVersionFromFile('/nonexistent/template.md'), isNull);
    });

    test('returns null for invalid UTF-8 without throwing', () {
      final dir = Directory.systemTemp.createTempSync('somnio_tv_');
      addTearDown(() => dir.deleteSync(recursive: true));
      final f = File('${dir.path}/t.md')..writeAsBytesSync([0xff, 0xfe, 0xfa]);
      expect(readTemplateVersionFromFile(f.path), isNull);
    });

    test('reads a file', () {
      final dir = Directory.systemTemp.createTempSync('somnio_tv_');
      addTearDown(() => dir.deleteSync(recursive: true));
      final f = File('${dir.path}/t.md')
        ..writeAsStringSync(_template('Somnio CLI v3.2.2'));
      expect(readTemplateVersionFromFile(f.path), '3.2.2');
    });
  });

  group('checkInstalledSkillVersion', () {
    test('equal versions pass', () {
      expect(
        checkInstalledSkillVersion(
          skillName: 'example-health-audit',
          installedVersion: '3.2.5',
          cliVersion: '3.2.5',
        ),
        isNull,
      );
    });

    test('older stamp aborts naming both versions', () {
      final msg = checkInstalledSkillVersion(
        skillName: 'example-health-audit',
        installedVersion: '3.2.2',
        cliVersion: '3.2.5',
      );
      expect(
        msg,
        'Installed example-health-audit skills are v3.2.2 but the CLI is '
        'v3.2.5. Run `somnio skills update` and retry.',
      );
    });

    test('missing stamp reports unknown install', () {
      final msg = checkInstalledSkillVersion(
        skillName: 'example-health-audit',
        installedVersion: null,
        cliVersion: '3.2.5',
      );
      expect(msg, contains('unknown install'));
      expect(msg, contains('somnio skills update'));
    });
  });

  group('checkInstalledTemplate', () {
    late Directory dir;
    setUp(() => dir = Directory.systemTemp.createTempSync('somnio_tv_'));
    tearDown(() => dir.deleteSync(recursive: true));

    String? check(String path) => checkInstalledTemplate(
          skillName: 'example-health-audit',
          templatePath: path,
          cliVersion: '3.2.5',
        );

    test('a current template passes', () {
      final f = File('${dir.path}/t.md')
        ..writeAsStringSync(_template('Somnio CLI v3.2.5'));
      expect(check(f.path), isNull);
    });

    test('a stale template names both versions', () {
      final f = File('${dir.path}/t.md')
        ..writeAsStringSync(_template('Somnio CLI v3.2.2'));
      final msg = check(f.path)!;
      expect(msg, contains('v3.2.2'));
      expect(msg, contains('v3.2.5'));
      expect(msg, isNot(contains('Template not found')));
    });

    test('a placeholder template reports unknown install', () {
      final f = File('${dir.path}/t.md')
        ..writeAsStringSync(_template('Somnio CLI vX.Y.Z'));
      final msg = check(f.path)!;
      expect(msg, contains('unknown install'));
      expect(msg, isNot(contains('Template not found')));
    });

    test('a missing template also names the path it looked up', () {
      final path = '${dir.path}/missing.md';
      final msg = check(path)!;
      expect(msg, contains('unknown install'));
      expect(msg, contains('somnio skills update'));
      expect(msg, contains('Template not found: $path'));
    });
  });

  group('formatInstalledStamps', () {
    test('matching stamp', () {
      expect(formatInstalledStamps(['3.2.5'], '3.2.5'), 'v3.2.5');
    });

    test('mismatch shows both versions', () {
      final out = formatInstalledStamps(['3.2.2'], '3.2.5');
      expect(out, contains('v3.2.2'));
      expect(out, contains('v3.2.5'));
      expect(out, contains('mismatch'));
    });

    test('unknown and empty', () {
      expect(formatInstalledStamps([null], '3.2.5'), contains('unknown'));
      expect(formatInstalledStamps([], '3.2.5'), '-');
    });
  });
}
