import 'dart:io';

final _generatedByRow = RegExp(
  r'^\|\s*Generated by\s*\|\s*Somnio CLI v(\S+?)\s*\|\s*$',
  multiLine: true,
);
final _fencedBlock =
    RegExp(r'^```.*?^```[^\n]*$', multiLine: true, dotAll: true);
final _semver = RegExp(r'^\d+\.\d+\.\d+([-+][0-9A-Za-z.-]+)?$');

/// Extracts the version stamped in the `Generated by` row of a report
/// template, or `null` when the row is missing or still a placeholder
/// (for example `vX.Y.Z`).
String? readTemplateVersion(String templateContent) {
  // Ignore fenced code blocks, which may hold example rows.
  final content = templateContent.replaceAll(_fencedBlock, '');
  final matches = _generatedByRow.allMatches(content).toList();
  // Zero rows is a missing stamp; several rows are ambiguous.
  if (matches.length != 1) return null;
  final version = matches.single.group(1)!;
  return _semver.hasMatch(version) ? version : null;
}

/// Reads the stamp of the template file at [path]; `null` when the file is
/// missing, unreadable or carries no valid stamp.
String? readTemplateVersionFromFile(String path) {
  try {
    final file = File(path);
    if (!file.existsSync()) return null;
    return readTemplateVersion(file.readAsStringSync());
  } on FileSystemException {
    return null;
  } on FormatException {
    return null;
  }
}

/// Returns an abort message when the installed skills do not match
/// [cliVersion], or `null` when they do.
String? checkInstalledSkillVersion({
  required String skillName,
  required String? installedVersion,
  required String cliVersion,
}) {
  if (installedVersion == null) {
    return 'Installed $skillName skills have no version stamp '
        '(unknown install). Run `somnio skills update` and retry.';
  }
  if (installedVersion != cliVersion) {
    return 'Installed $skillName skills are v$installedVersion but the CLI '
        'is v$cliVersion. Run `somnio skills update` and retry.';
  }
  return null;
}

/// Checks the report template installed at [templatePath] against
/// [cliVersion] and returns an abort message, or `null` when they match.
///
/// A missing template file gets the unknown-install message plus the path
/// that was looked up, so a missing install is told apart from a template
/// with no valid stamp.
String? checkInstalledTemplate({
  required String skillName,
  required String templatePath,
  required String cliVersion,
}) {
  final error = checkInstalledSkillVersion(
    skillName: skillName,
    installedVersion: readTemplateVersionFromFile(templatePath),
    cliVersion: cliVersion,
  );
  if (error == null) return null;
  final isFile =
      FileSystemEntity.typeSync(templatePath) == FileSystemEntityType.file;
  return isFile ? error : '$error\nTemplate not found: $templatePath';
}

/// Formats the installed template stamps for `somnio status`.
///
/// A `null` entry is an install without a valid stamp. Any stamp that differs
/// from [cliVersion] is marked with both versions.
String formatInstalledStamps(Iterable<String?> stamps, String cliVersion) {
  if (stamps.isEmpty) return '-';
  final labels = stamps.toSet().map((v) {
    if (v == null) return 'unknown (CLI v$cliVersion)';
    if (v == cliVersion) return 'v$v';
    return 'v$v (mismatch, CLI v$cliVersion)';
  }).toList()
    ..sort();
  return labels.join(', ');
}
