// Every report-writing skill must carry the real CLI version in its report
// template, so a report written by any channel (somnio run, an in-session
// skill, a `somnio skills install` copy or the Cowork plugin) ends with
// `| Generated by | Somnio CLI v<packageVersion> |`. Fix a failure by running
// `dart run tool/stamp_version.dart` from cli/.
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:somnio/src/version.dart';
import 'package:test/test.dart';

final _generatedByRow = RegExp(r'^\| Generated by \|.*$', multiLine: true);

String _repoRoot() {
  var dir = Directory.current;
  while (true) {
    if (Directory(p.join(dir.path, 'skills')).existsSync()) return dir.path;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('Could not locate repo root from ${Directory.current}');
    }
    dir = parent;
  }
}

/// Every `.md` file under skills/ that may carry a `Generated by` row:
/// the template, SKILL.md and the agents of each skill.
List<File> _candidateFiles(Directory skills) => [
      for (final dir in skills.listSync().whereType<Directory>())
        for (final f in [
          File(p.join(dir.path, 'SKILL.md')),
          File(p.join(dir.path, 'assets', 'report-template.md')),
          if (Directory(p.join(dir.path, 'agents')).existsSync())
            ...Directory(p.join(dir.path, 'agents'))
                .listSync()
                .whereType<File>()
                .where((f) => f.path.endsWith('.md')),
        ])
          if (f.existsSync()) f,
    ];

/// The 19 skills that write a report with a `Report Metadata` table.
///
/// Listed explicitly so a template that loses its `Generated by` row still
/// fails its own test instead of silently dropping out of the check.
const _reportWritingSkills = [
  'angular-best-practices',
  'angular-health-audit',
  'angularjs-best-practices',
  'angularjs-health-audit',
  'dora-metrics',
  'dotnet-best-practices',
  'dotnet-health-audit',
  'flutter-best-practices',
  'flutter-health-audit',
  'harness-audit',
  'iso27001-audit',
  'nestjs-best-practices',
  'nestjs-health-audit',
  'python-best-practices',
  'python-health-audit',
  'react-best-practices',
  'react-health-audit',
  'security-audit',
  'soc2-audit',
];

/// The skills whose SKILL.md declares a `Report Metadata (MANDATORY)`
/// section or whose template carries a `Generated by` row.
Set<String> _declaredReportSkills(Directory skills) => {
      for (final dir in skills.listSync().whereType<Directory>())
        if (File(p.join(dir.path, 'SKILL.md')).existsSync() &&
                File(p.join(dir.path, 'SKILL.md'))
                    .readAsStringSync()
                    .contains('Report Metadata (MANDATORY)') ||
            File(p.join(dir.path, 'assets', 'report-template.md'))
                    .existsSync() &&
                _generatedByRow.hasMatch(
                  File(p.join(dir.path, 'assets', 'report-template.md'))
                      .readAsStringSync(),
                ))
          p.basename(dir.path),
    };

void main() {
  final skills = Directory(p.join(_repoRoot(), 'skills'));
  final expectedRow = '| Generated by | Somnio CLI v$packageVersion |';

  test('every skill that declares a report is in the report-writing list', () {
    expect(
      _declaredReportSkills(skills).difference(_reportWritingSkills.toSet()),
      isEmpty,
      reason: 'add the skill to _reportWritingSkills and give its template '
          'the Generated by row',
    );
  });

  group('Generated by row equals Somnio CLI v$packageVersion', () {
    for (final skill in _reportWritingSkills) {
      test('$skill template', () {
        final file =
            File(p.join(skills.path, skill, 'assets', 'report-template.md'));
        final rows = file.existsSync()
            ? _generatedByRow
                .allMatches(file.readAsStringSync())
                .map((m) => m.group(0)!.trimRight())
                .toList()
            : <String>[];
        expect(rows, [expectedRow],
            reason: 'the template must carry exactly one stamped row; run '
                '`dart run tool/stamp_version.dart` from cli/');
      });
    }
  });

  test('no SKILL.md, agent or template carries a stale or placeholder stamp',
      () {
    final offenders = <String>[];
    for (final file in _candidateFiles(skills)) {
      for (final m in _generatedByRow.allMatches(file.readAsStringSync())) {
        if (m.group(0)!.trimRight() != expectedRow) {
          offenders.add('${p.relative(file.path, from: skills.path)}: '
              '${m.group(0)}');
        }
      }
    }
    expect(offenders, isEmpty,
        reason: 'run `dart run tool/stamp_version.dart` from cli/');
  });

  test('dora_metrics.py SOMNIO_VERSION equals packageVersion', () {
    final source =
        File(p.join(skills.path, 'dora-metrics', 'scripts', 'dora_metrics.py'))
            .readAsStringSync();
    final match = RegExp(r'^SOMNIO_VERSION = "([^"]*)"', multiLine: true)
        .firstMatch(source);
    expect(match, isNotNull, reason: 'SOMNIO_VERSION constant is missing');
    expect(match!.group(1), packageVersion,
        reason: 'run `dart run tool/stamp_version.dart` from cli/');
  });
}
