@TestOn('!windows')
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:somnio/src/content/skill_registry.dart';
import 'package:somnio/src/version.dart';
import 'package:test/test.dart';

/// `status_command.dart` is coverage:ignore-file and reads the real HOME, so
/// these tests drive `somnio status` as a subprocess with a temporary HOME.
void main() {
  late Directory sandbox;
  late String home;

  setUp(() {
    sandbox = Directory.systemTemp.createTempSync('somnio_status_');
    home = p.join(sandbox.path, 'home');
  });

  tearDown(() => sandbox.deleteSync(recursive: true));

  String cliScript() {
    final inCli = p.join(Directory.current.path, 'bin', 'somnio.dart');
    if (File(inCli).existsSync()) return inCli;
    return p.join(Directory.current.path, 'cli', 'bin', 'somnio.dart');
  }

  /// Installs a minimal Claude security-audit skill whose template carries
  /// [generatedBy], or no template at all when it is `null`.
  void installSecurityAudit(String? generatedBy) {
    final bundle = SkillRegistry.findById('security_audit')!;
    final skillDir = p.join(home, '.claude', 'skills', bundle.name);
    File(p.join(skillDir, 'SKILL.md'))
      ..createSync(recursive: true)
      ..writeAsStringSync('---\nname: ${bundle.name}\n---\n');
    File(p.join(skillDir, 'references', 'report-generator.md'))
      ..createSync(recursive: true)
      ..writeAsStringSync('# Report generator\n');
    if (generatedBy == null) return;
    final templateFile = bundle.templatePath!.split('/').last;
    File(p.join(skillDir, 'assets', templateFile))
      ..createSync(recursive: true)
      ..writeAsStringSync(
        '## 12. Report Metadata\n\n| Field | Value |\n|---|---|\n'
        '| Generated by | $generatedBy |\n| Skill | security-audit |\n',
      );
  }

  Future<String> runStatus() async {
    final result = await Process.run(
      Platform.resolvedExecutable,
      [cliScript(), 'status'],
      environment: {'HOME': home},
    );
    expect(result.exitCode, 0, reason: '${result.stderr}');
    return '${result.stdout}';
  }

  const timeout = Timeout(Duration(minutes: 2));

  test(
    'shows the CLI version and marks a mismatched stamp with both versions',
    () async {
      installSecurityAudit('Somnio CLI v0.0.1');
      final out = await runStatus();
      expect(out, contains('Somnio CLI v$packageVersion'));
      expect(out, contains('Stamp'));
      expect(out, contains('v0.0.1 (mismatch, CLI v$packageVersion)'));
    },
    timeout: timeout,
  );

  test(
    'shows a matching stamp without a mismatch mark',
    () async {
      installSecurityAudit('Somnio CLI v$packageVersion');
      final out = await runStatus();
      expect(out, contains('v$packageVersion'));
      expect(out, isNot(contains('mismatch')));
    },
    timeout: timeout,
  );

  test(
    'marks an install whose template is missing as unknown',
    () async {
      installSecurityAudit(null);
      final out = await runStatus();
      expect(out, contains('unknown (CLI v$packageVersion)'));
    },
    timeout: timeout,
  );
}
