// Covers the release helper tool/stamp_version.dart on a temporary copy of
// the skills tree; the repo itself is never mutated.
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:test/test.dart';

import '../../tool/stamp_version.dart';

Directory _repoRoot() {
  var dir = Directory.current;
  while (true) {
    if (Directory(p.join(dir.path, 'skills')).existsSync()) return dir;
    final parent = dir.parent;
    if (parent.path == dir.path) {
      throw StateError('Could not locate repo root from ${Directory.current}');
    }
    dir = parent;
  }
}

void _copy(Directory from, Directory to) {
  to.createSync(recursive: true);
  for (final e in from.listSync(followLinks: false)) {
    final name = p.basename(e.path);
    if (e is Directory) {
      _copy(e, Directory(p.join(to.path, name)));
    } else if (e is File) {
      e.copySync(p.join(to.path, name));
    }
  }
}

void main() {
  late Directory tmp;
  late String version;

  setUp(() {
    tmp = Directory.systemTemp.createTempSync('stamp_version_test_');
    final skills = Directory(p.join(_repoRoot().path, 'skills'));
    _copy(skills, Directory(p.join(tmp.path, 'skills')));
    version = RegExp(r'^SOMNIO_VERSION = "([^"]*)"', multiLine: true)
        .firstMatch(File(p.join(tmp.path, 'skills', 'dora-metrics', 'scripts',
                'dora_metrics.py'))
            .readAsStringSync())!
        .group(1)!;
  });

  tearDown(() => tmp.deleteSync(recursive: true));

  test('a clean tree changes nothing and reports no missing row', () {
    final result = stampVersion(tmp.path, version);
    expect(result.changed, isEmpty);
    expect(result.missingRow, isEmpty);
  });

  test('a report-writing template without the row is reported by path', () {
    final template = File(p.join(
        tmp.path, 'skills', 'security-audit', 'assets', 'report-template.md'));
    template.writeAsStringSync(template
        .readAsStringSync()
        .split('\n')
        .where((l) => !l.startsWith('| Generated by |'))
        .join('\n'));

    final result = stampVersion(tmp.path, version);
    expect(result.missingRow,
        [p.join('skills', 'security-audit', 'assets', 'report-template.md')]);
  });

  group('runStamp', () {
    late String cliRoot;
    late StringBuffer out;
    late StringBuffer err;

    setUp(() {
      cliRoot = p.join(tmp.path, 'cli');
      Directory(p.join(cliRoot, 'lib', 'src')).createSync(recursive: true);
      File(p.join(cliRoot, 'lib', 'src', 'version.dart'))
          .writeAsStringSync("const packageVersion = '$version';\n");
      out = StringBuffer();
      err = StringBuffer();
    });

    test('exits 0 with the no-op message on a clean tree', () {
      expect(runStamp(cliRoot, out: out, err: err), 0);
      expect(
        out.toString(),
        'Already stamped with v$version, nothing to change.\n',
      );
      expect(err.toString(), isEmpty);
    });

    test('exits non-zero and names the template on stderr when it lost its row',
        () {
      final template = File(p.join(
          tmp.path, 'skills', 'soc2-audit', 'assets', 'report-template.md'));
      template.writeAsStringSync(template
          .readAsStringSync()
          .split('\n')
          .where((l) => !l.startsWith('| Generated by |'))
          .join('\n'));

      expect(runStamp(cliRoot, out: out, err: err), 2);
      expect(
        err.toString(),
        contains(
            p.join('skills', 'soc2-audit', 'assets', 'report-template.md')),
      );
      expect(out.toString(), isNot(contains('report-template.md')));
    });
  });
}
